// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMUMejloxuVU6T3TqonMQIyEpAJsMs-5M',
    appId: '1:15287572084:web:fcb83d1d219e61f8e6a321',
    messagingSenderId: '15287572084',
    projectId: 'prueba-0109',
    authDomain: 'prueba-0109.firebaseapp.com',
    storageBucket: 'prueba-0109.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvpbAh2ew_AQIoolJFrz5sJajpKrQfy0',
    appId: '1:15287572084:android:3fa2bdff4be23c11e6a321',
    messagingSenderId: '15287572084',
    projectId: 'prueba-0109',
    storageBucket: 'prueba-0109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLLLWRQX0MsMBJQGKyTXtS9U0SkFIbESA',
    appId: '1:15287572084:ios:0a643ce96b9e4fd3e6a321',
    messagingSenderId: '15287572084',
    projectId: 'prueba-0109',
    storageBucket: 'prueba-0109.appspot.com',
    androidClientId: '15287572084-m04hmm6qg2qk9of6j80l0a0h6n52ln5f.apps.googleusercontent.com',
    iosClientId: '15287572084-ravgj0vqkc46987f0fhvhrgjlbuh0io5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLLLWRQX0MsMBJQGKyTXtS9U0SkFIbESA',
    appId: '1:15287572084:ios:0a643ce96b9e4fd3e6a321',
    messagingSenderId: '15287572084',
    projectId: 'prueba-0109',
    storageBucket: 'prueba-0109.appspot.com',
    androidClientId: '15287572084-m04hmm6qg2qk9of6j80l0a0h6n52ln5f.apps.googleusercontent.com',
    iosClientId: '15287572084-ravgj0vqkc46987f0fhvhrgjlbuh0io5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMUMejloxuVU6T3TqonMQIyEpAJsMs-5M',
    appId: '1:15287572084:web:7886685b90dd80ede6a321',
    messagingSenderId: '15287572084',
    projectId: 'prueba-0109',
    authDomain: 'prueba-0109.firebaseapp.com',
    storageBucket: 'prueba-0109.appspot.com',
  );
}
